version: '3.10.10'
services:
  ####################
  app:
    build: .
    command: sh -c 'alembic upgrade head && python -m app'
    volumes:
      - ./:/app
      - static_volume:/home/app/web/backend_static
      - media_volume:/home/app/web/backend_media
    working_dir: /app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - database
  ####################
  database:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app_network
    ports:
      - "5400:5432"
  ###################
volumes:
  postgres_data:
  static_volume:
  media_volume:
networks:
  app_network: