version: '3.10.10'
services:
  ####################
  app:
    build: .
    command: sh -c 'python -m app'
    volumes:
      - ./:/app
      - static_volume:/home/app/web/backend_static
      - media_volume:/home/app/web/backend_media
    working_dir: /app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network
  ####################
volumes:
  postgres_data:
  static_volume:
  media_volume:
networks:
  app_network: