version: '3.10.10'
services:
  ####################
  app:
    build: .
    command: sh -c 'alembic upgrade head && python -m app'
    volumes:
      - ./:/app
      - static_volume:/home/app/web/backend_static
      - media_volume:/home/app/web/backend_media
    working_dir: /app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - database
  ####################
  database:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app_network
    ports:
      - "5400:5432"
  ###################
  redis:
    image: redis:latest
    restart: always
    networks:
      - app_network
  ###################
  celery:
    build: .
    working_dir: /app
    restart: always

    container_name: celery_worker
    command: celery -A app.services.tasks.worker worker -l info
    networks:
      - app_network
    depends_on:
      - redis
    ##################
  celery-beat:
    build: .
    restart: always
    working_dir: /app
    command: "celery -A app.services.tasks.worker beat -l info"
    networks:
      - app_network
    depends_on:
      - redis
      - celery
  flower:
    build: .
    restart: always
    container_name: flower
    working_dir: /app
    command: >
      bash -c "celery -A app.services.tasks.worker flower --port=5566 &&
      celery -A app.services.tasks.worker flower --address=0.0.0.0 --port=5566 &&
      celery -A app.services.tasks.worker flower --broker=redis://redis:6379"
    networks:
      - app_network
    ports:
      - '5566:5566'
    depends_on:
      - celery
      - redis
  ######################
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - static_volume:/home/app/web/backend_static
      - media_volume:/home/app/web/backend_media
    networks:
      - app_network
    depends_on:
      - app
  ######################
volumes:
  postgres_data:
  static_volume:
  media_volume:
networks:
  app_network: